# Generated by Django 2.2.3 on 2019-07-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsTutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
