# Generated by Django 2.2.3 on 2019-07-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsTutorial', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chart_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
